[project]
name = "Gridfinity Extended"
uri = "https://github.com/ostat/gridfinity_extended_openscad"
export-filename-prefix = "Gridfinity Extended"
mode = "multi"
head-extra = ''

[[model]]
file = "gridfinity_basic_cup.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[model.tab-metadata."General Cup"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#general-cup-settings"
collapsed = true

[model.tab-metadata."Cup Lip"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#cuplip"
collapsed = true

[model.tab-metadata."Subdivisions"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#subdivisions"
collapsed = true

[model.tab-metadata."Base"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#base"
collapsed = true
[model.param-metadata.magnet_size]
display-condition = {js = "enable_magnets"}
[model.param-metadata.magnet_easy_release]
display-condition = {js = "enable_magnets"}
[model.param-metadata.magnet_side_access]
display-condition = {js = "enable_magnets"}
[model.param-metadata.magnet_captive_height]
display-condition = {js = "enable_magnets"}
[model.param-metadata.magnet_crush_depth]
display-condition = {js = "enable_magnets"}
[model.param-metadata.magnet_chamfer]
display-condition = {js = "enable_magnets"}
[model.param-metadata.screw_size]
display-condition = {js = "enable_screws"}

[model.tab-metadata."Label"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#label"
collapsed = true

[model.tab-metadata."Sliding Lid"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#slidinglid"
collapsed = true
[model.param-metadata.sliding_lid_enabled]
[model.param-metadata.sliding_lid_thickness]
display-condition = {js = "sliding_lid_enabled"}
[model.param-metadata.sliding_lid_min_wall_thickness]
display-condition = {js = "sliding_lid_enabled"}
[model.param-metadata.sliding_lid_min_support]
display-condition = {js = "sliding_lid_enabled"}
[model.param-metadata.sliding_lid_clearance]
display-condition = {js = "sliding_lid_enabled"}
[model.param-metadata.sliding_lid_pull_style]
display-condition = {js = "sliding_lid_enabled"}
[model.param-metadata.sliding_lid_pull_style]
display-condition = {js = "sliding_lid_nub_size"}

[model.tab-metadata."Finger Slide"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#fingerslide"
collapsed = true

[model.tab-metadata."Tapered Corner"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#taperedcorner"
collapsed = true

[model.tab-metadata."Wall Pattern"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#wallpattern"
collapsed = true
[model.param-metadata.wallpattern_enabled]
[model.param-metadata.wallpattern_style]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_strength]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_walls]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_rotate_grid]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_cell_size]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_dividers_enabled]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_hole_sides]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_hole_radius]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_fill]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_border]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_depth]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_pattern_voronoi_noise]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_pattern_brick_weight]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_pattern_quality]
display-condition = {js = "wallpattern_enabled"}
[model.param-metadata.wallpattern_colored]
display-condition = {js = "wallpattern_enabled"}

[model.tab-metadata."Floor Pattern"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#floorpattern"
collapsed = true
[model.param-metadata.floorpattern_enabled]
[model.param-metadata.floorpattern_style]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_strength]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_rotate_grid]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_cell_size]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_hole_sides]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_hole_radius]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_fill]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_border]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_depth]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_pattern_grid_chamfer]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_pattern_voronoi_noise]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_pattern_brick_weight]
display-condition = {js = "floorpattern_enabled"}
[model.param-metadata.floorpattern_pattern_quality]
display-condition = {js = "floorpattern_enabled"}

[model.tab-metadata."Wall Cutout"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#wallcutout"
collapsed = true

[model.tab-metadata."Extendable"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#extendable"
collapsed = true

[model.tab-metadata."Bottom Text"]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#bottomtext"
collapsed = true

[model.tab-metadata."debug"]
collapsed = true

[model.tab-metadata."Model detail"]
collapsed = true

[[model]]
file = "gridfinity_baseplate.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_item_holder.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_drawers.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_lid.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_marble.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_tray.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_vertical_divider.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "stanley_basic_cup.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_baseplate_flsun_q5.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_chess.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_glue_stick.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_sieve.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_silverware_legacy.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_silverware.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_sliding_lid.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[[model]]
file = "gridfinity_socket_holder.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."

[model.param-metadata.magnet_size]
help-link = "https://docs.ostat.com/docs/openscad/gridfinity-extended/basic-cup/#base"
display-condition = {js = "enable_magnets"}