[project]
name = "Gridfinity Extended"
uri = "https://github.com/ostat/gridfinity_extended_openscad"
export-filename-prefix = "Gridfinity Extended"
mode = "single"
head-extra = ''

[[model]]
file = "combined/gridfinity_basic_cup.scad"
description-extra-html = "<br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>."